enum BookOrderBy {
  TITLE
  AUTHOR
  PUBLICATION_DATE
  AVG_RATING
  NB_REVIEWS
  IS_IN_FAVORITE
  IS_IN_LIBRARY
  CREATED_AT
  GENRE
}

enum BookGenre {
  FICTION
  NON_FICTION
  SCIENCE_FICTION
  FANTASY
  ROMANCE
  THRILLER
  MYSTERY
  BIOGRAPHY
  HISTORY
  SCIENCE
  OTHER
}

enum AgeLimit {
  ALL_AGES
  TEEN_13_PLUS
  MATURE_16_PLUS
  ADULT_18_PLUS
}