enum UserOrderBy {
  NAME
  EMAIL
  PSEUDO
  ROLE
  STATUS
  CREATED_AT
}

enum UserStatus {
  1              # ACTIVE
  2              # BLOCKED_BY_ADMIN
  3              # BLOCKED_BY_USER
  4              # BLOCKED_BY_BOTH
  5              # DELETED
}

