enum ReportType {
  USER
  REVIEW
  MESSAGE
  OTHER
}

enum ReportStatus {
  PENDING
  IN_REVIEW
  RESOLVED
  DISMISSED
}

enum ReportOrderBy {
  CREATED_AT
  STATUS
  REPORT_TYPE
}
enum ReportReason {
  HARASSMENT_INSULTS
  HATEFUL_DISCRIMINATORY_CONTENT
  SPAM_UNSOLICITED_ADVERTISING
  IDENTITY_IMPERSONATION
  SPREADING_FALSE_INFORMATION
  SHARING_PERSONAL_INFORMATION
  THREATS_CALLS_TO_VIOLENCE
  PORNOGRAPHY_EXPLICIT_CONTENT
  INAPPROPRIATE_CONTENT_FOR_MINORS
  COPYRIGHT_VIOLATION
  SCAM_FRAUD_ATTEMPT
  AGGRESSIVE_BEHAVIOR_IN_PRIVATE_MESSAGES
  DEFAMATORY_COMMENT
  TARGETED_REPEATED_HARASSMENT
  PUBLICATION_OF_SENSITIVE_BANK_DETAILS
  OFFENSIVE_CONTENT_RELATED_TO_RELIGION
  COMMUNITY_RULES_VIOLATION
  TERMS_OF_SERVICE_VIOLATION
  MISLEADING_CONTENT_CLICKBAIT_PHISHING
  OTHER_SPECIFY_IN_DETAILS  
}