enum ReasonOfReport {
    HARASSMENT_INSULTING_LANGUAGE 
    HATEFUL_DISCRIMINATORY_CONTENT
    SPAM_UNSOLICITED_ADVERTISING
    IMPERSONATION
    SPREAD_OF_FALSE_INFORMATION
    SHARING_OF_PERSONAL_INFORMATION_DOXING
    THREATS_CALLS_FOR_VIOLENCE
    PORNOGRAPHY_EXPLICIT_SEXUAL_CONTENT
    INAPPROPRIATE_CONTENT_FOR_MINORS
    COPYRIGHT_INFRINGEMENT
    SCAM_ATTEMPTED_FRAUD
    AGGRESSIVE_BEHAVIOR_IN_PRIVATE_MESSAGES
    DEFAMATORY_COMMENT
    REPEATED_TARGETED_HARASSMENT
    POSTING_OF_BANKING_SENSITIVE_INFORMATION
    OFFENSIVE_CONTENT_RELATED_TO_RELIGION
    VIOLATION_OF_COMMUNITY_RULES
    NON_COMPLIANCE_WITH_TERMS_OF_SERVICE
    MISLEADING_CONTENT
    OTHER_SPECIFY_IN_DETAILS
}

