enum MessageOrderBy {
  ID_SENDER
  ID_RECEIVER
  SUBJECT
  CONTENT
  IS_READ
  UPDATED_AT
}

emum MessageFilter {
  ID_SENDER
  ID_RECEIVER
  SUBJECT
  CONTENT
  IS_READ
  CREATED_AT
  UPDATED_AT
}
enum MessageSearchBy {
  SUBJECT
  CONTENT
}
enum MessageSubject {
  NOUVELLE_FONCTIONNALITE
  PROBLEME_CONNEXION
  MISE_A_JOUR_PREFERENCES
  INVITATION_BIBLIOTHEQUE
  CONFIRMATION_SUPPRESSION
  MESSAGE_PRIVÉ
  NOTIFICATION_SECURITE
  SUGGESTIONS_LECTURE
  RAPPORT_SIGNALE
  BIENVENUE_COMMUNAUTE
}