# Étape 1 : Build du frontend
FROM node:20-alpine AS build

WORKDIR /app-frontend

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

# Étape 2 : Image finale avec Nginx
FROM nginx:alpine

WORKDIR /usr/share/nginx/html
COPY --from=build /app-frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf


# Exposer le port 80 pour Nginx
EXPOSE 80

# Nginx se lance par défaut via son ENTRYPOINT