    type PaginatedReports {
        reports: [Report!]!
        totalCount: Int!
        hasNextPage: Boolean!
        httpStatus: Int
    }

extend type Query {        # Type pour les résultats de recherche paginés
        # Récupérer tous les rapports
        getReports(
            limit: Int, 
            offset: Int, 
            order: String = "created_at", # Colonne par défaut pour le tri
            direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
        ): PaginatedReports!

        # Récupérer un rapport par son ID
        getReport(id_report: ID!): Report 

        # Rechercher des rapports par utilisateur avec pagination
        searchReportsByUser(id_user: ID!, limit: Int, offset: Int): PaginatedReports!

        # Rechercher des rapports par statut avec pagination
        searchReportsByStatus(status: String!, limit: Int, offset: Int): PaginatedReports!

        # Rechercher des rapports par contenu spécifique avec pagination
        searchReportsByDetailsOrReason(content: String!, limit: Int, offset: Int): PaginatedReports!

        # Recherche des rapports avec filtres multiples et pagination
        searchReports(id_report: ID, id_user: ID, status: String, content: String, limit: Int, offset: Int): PaginatedReports!



}