# Type pour les résultats de recherche paginés

type PaginatedAuthors {
    authors: [Author!]!
    totalCount: Int!
    hasNextPage: Boolean!
    httpStatus: Int  
}

extend type Query {
    # Récupérer tous les auteurs
    getAllAuthors(
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedAuthors!

    getAuthorByID(
        id_author: ID!
    ): Author

    getAuthorByName(
        name: String!
    ): Author

    searchAuthorsByName(
        name: String!, 
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedAuthors!

    searchAuthors(
        name: String!, 
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedAuthors!

}   




