type PaginatedLibraries {
  libraries: [Library!]!
  totalCount: Int!
  hasNextPage: Boolean!
  httpStatus: Int
}

extend type Query {
  # Récupérer toutes les bibliothèques
  getLibraries(
    limit: Int
    offset: Int
    order: String = "created_at"
    direction: String = "ASC"
  ): PaginatedLibraries

  # Récupérer les bibliothèques de l'utilisateur connecté
  getUserLibraries(
    limit: Int
    offset: Int
    order: String = "created_at"
    direction: String = "ASC"
  ): PaginatedLibraries

  # Récupérer une bibliothèque par son ID
  getLibrary(id_library: ID!): Library

  # Récupérer toutes les bibliothèques de l'utilisateur connecté
  getMyLibraries(filter: LibraryFilterInput): [Library!]!

  # Obtenir les bibliothèques publiques d'un utilisateur
  getPublicLibraries(id_user: ID!): [Library!]!

  # Rechercher des bibliothèques par nom
  searchLibraries(name: String!, limit: Int, offset: Int): PaginatedLibraries

  getLibrariesByIdUser(id_user: ID!, limit: Int, offset: Int): PaginatedLibraries







GetMyLibrariesWithBooks(id_user: ID!, limit: Int, offset: Int): PaginatedLibraries









}