# Type pour les résultats de recherche paginés
type PaginatedBooksInLibrary {
    books: [BookHasLibrary!]!
    totalCount: Int!
    hasNextPage: Boolean!
    httpStatus: Int  
}


type LibraryWithBooks {
  id_library: ID!
  name: String
  bookCount: Int!
  books: [BookHasLibrary!]!
}
 type PaginatedBooksInMyLibrary {
  libraries: [LibraryWithBooks!]!
}

extend type Query {
    # Récupérer tous les livres en bibliothèque
    getAllBooksAllLibrariesForAdmin(
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedBooksInLibrary!

    get_AllBooksAllLibrariesForAdmin(
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedBooksInLibrary!

    # Récupérer tous les livres de toutes LES bibliothèques de l'utilisateur connecté
    getAllBooksInAllMyLibraries(
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedBooksInMyLibrary!

    getAllBooksIn1Library(
        id_library: ID!, 
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedBooksInLibrary!

    # Récupérer un livre en bibliothèque par son ID
    getBookInLibrary(
        id_bookhaslibrary: ID!,
        limit: Int, 
        offset: Int,
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
        ): BookHasLibrary 

    # Rechercher des livres en bibliothèque par titre ou auteur avec pagination
    searchBooksInLibrary(titleOrAuthor: String!, limit: Int, offset: Int): PaginatedBooksInLibrary!

    getMyBooksInLibraries(
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC
    ): PaginatedBooksInLibrary!

    getAllBookInLibrariesOfUserForAdmin(
        id_user: ID!,
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedBooksInMyLibrary!

  #Récupérer les livres d'une bibliothèque avec filtres
  getBooksInLibrary(
    id_library: ID!
    filter: BookInLibraryFilterInput
    ): [BookHasLibrary!]!
  
  # Rechercher dans toutes mes bibliothèques
    searchInAllLibraries(search: String!): [BookHasLibrary!]!














    IsBookInFavorites(id_book: ID!): Boolean!





}