# Type pour les résultats de recherche paginés

type PaginatedPasswordResets {
    passwordResets: [PasswordReset!]!
    totalCount: Int!
    hasNextPage: Boolean!
    httpStatus: Int  
}

extend type Query {
    # Récupérer tous les types de signalement
    getAllPasswordResets(
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedPasswordResets!

    getPasswordResetByID(
        id_passwordReset: ID!
    ): PasswordReset

    getPasswordResetByEmail(
        email: String!
    ): [PasswordReset!]!

    searchPasswordResetByEmail(
        email: String!, 
        limit: Int, 
        offset: Int, 
        order: String = "created_at", # Colonne par défaut pour le tri
        direction: String = "ASC" # Direction par défaut pour le tri (ASC ou DESC)
    ): PaginatedPasswordResets!

}
