schema {
  query: Query
  mutation: Mutation

}

type Query {
  _empty: String
}

type Mutation {
  _empty: String
}

# schema.gql
# Ce fichier sert de point d'entrée pour la documentation
# Les types sont chargés automatiquement depuis les sous-dossiers

# Structure du schéma :
# - scalars/ : Types scalaires personnalisés (Date, DateTime)
# - types/ : Définitions des types GraphQL
# - enums/ : Énumérations
# - connections/ : Types de connexion Relay
# - inputs/ : Types d'entrée pour les mutations
# - queries/ : Requêtes disponibles
# - mutations/ : Mutations disponibles