input CreateLibraryInput {
  name: String!
  is_editable: Boolean!
  id_user: ID!
  is_default: Boolean!
  color: String!
  is_public: Boolean!
  description: String
  sort_order: Int
  created_at: DateTime
  updated_at: DateTime
}

input UpdateLibraryInput {
  name: String!
  is_editable: Boolean!
  id_user: ID!
  is_default: Boolean!
  color: String!
  is_public: Boolean!
  description: String
  sort_order: Int
  created_at: DateTime
  updated_at: DateTime
}

input DeleteLibraryInput {
  id_library: ID!
}


