
input RequestPasswordResetInput {
  email: String!
}

input ResetPasswordInput {
  resetCode: String!
  newPassword: String!
}

input VerifyResetCodeInput {
  resetCode: String!
}

input AdminResetPasswordInput {
  newPassword: String!
}

input ChangePasswordInput {
  currentPassword: String!
  newPassword: String!
}

input UnblockAccountInput {
  id_user: ID!
}

input RequestAdminUnblockInput {
  email: String!
}

input CreatePasswordResetCodeInput {
  email: String!
}

input ResetPasswordWithCodeInput {
  resetCode: String!
  newPassword: String!
}

input DeletePasswordResetCodeInput {
  resetCode: String!
}

input UpdateUserRoleInput {
  id_user: ID!
  id_role: ID!
}
