input CreateRoleHasPermissionInput {
  id_rolehaspermission: ID
  id_role: ID!
  id_permission: ID!
}

input UpdateRoleHasPermissionInput {
  id_rolehaspermission: ID!
  id_role: ID
  id_permission: ID
}

input DeleteRoleHasPermissionInput {
  id_rolehaspermission: ID!
}

