input CreateUserInput {
  name: String!
  email: String!
  password: String!
  pseudo: String!
  id_role: String
}

input UpdateUserInput {
  id_user: ID!
  name: String
  email: String
  pseudo: String
  status: String
  id_role: String
}

input DeleteUserInput {
  id_user: ID!
}

# Mutation séparée pour le mot de passe
input ChangePasswordInput {
  id_user: ID!
  oldPassword: String!
  newPassword: String! 
}


input UserSortInput {
  orderBy: UserOrderBy!
  direction: OrderDirection!
}

# Pour l'inscription publique
input RegisterUserInput {
  name: String
  email: String!
  password: String!
  pseudo: String!
}

# Pour l'admin seulement
input AdminCreateUserInput {
  name: String
  email: String!
  password: String!
  pseudo: String!
  idRole: ID
  isActive: Boolean
}

# Pour la mise à jour par l'utilisateur
input UpdateUserInput {
  name: String
  email: String
  pseudo: String
}

# Pour la mise à jour par l'admin
input AdminUpdateUserInput {
  idUser: ID!
  name: String
  email: String
  pseudo: String
  idRole: ID
  isActive: Boolean
}