input CreateStatisticInput {
  total_books: Int!
  books_read: Int!
  books_reading: Int!
  books_to_read: Int!
  avg_rating: Float
  total_pages: Int
  books_lent: Int!
}

input UpdateStatisticInput {
  total_books: Int!
  books_read: Int!
  books_reading: Int!
  books_to_read: Int!
  avg_rating: Float
  total_pages: Int
  books_lent: Int!
}

input DeleteStatisticInput {
  id_statistic: ID!
}