input CreateLibraryInput {
  name: String!
  isEditable: Boolean
  id_user: String!
}

input UpdateLibraryInput {
  id_library: ID!
  name: String
  isEditable: Boolean
}

input DeleteLibraryInput {
  id_library: ID!
}
