input CreateBookInput {
  title: String!
  author: String
  genre: String
  isbn: String
  publication_date: Date
  editor: String
  vignetteimage: String
  bookimage: String
  age_limit: Int
  description: String
  series: String

}

input UpdateBookInput {
  title: String
  author: String
  genre: String
  isbn: String
  publication_date: String
  editor: String
  vignetteimage: String
  bookimage: String
  age_limit: Int
  description: String
  series: String
  minRating: Float
  maxRating: Float
}


input DeleteBookInput {
  id_book: ID!
}
input BookFilter {
  title: String
  author: String
  genre: String
  minRating: Float
  maxRating: Float
  ageLimit: Int
  publicationDate: DateRangeInput
  minAge: Int
  maxAge: Int

}

input BookSort {
  orderBy: BookOrderBy!
  direction: OrderDirection!
}