input CreateRoleHasPermissionInput {
  id_rolehaspermission: ID
  roleId: ID!
  permissionId: ID!
}

input UpdateRoleHasPermissionInput {
  id_rolehaspermission: ID!
  roleId: ID
  permissionId: ID
}

input DeleteRoleHasPermissionInput {
  id_rolehaspermission: ID!
}

