# Type pour représenter un livre
type Book {
  id_book: ID! # Utilisation de ID pour les identifiants uniques
  title: String
  isbn: String
  publication_date: String # Utilisation de String pour les dates (format ISO 8601 recommandé)
  author: String
  editor: String
  genre: String
  vignetteimage: String
  bookimage: String
  age_limit: Int
  description: String
  series: String
  is_in_favorite: Int # combien d'utilisateurs ont ce livre en favori
  nb_reviews: Int
  is_in_library: Int # combien d'utilisateurs ont ce livre dans leur bibliothèque
  avg_rating: Float
  created_at: Date 
  updated_at: Date
  # Relations
}

