# Type pour représenter une bibliothèque
type Library {
  id_library: ID!
  name: String!
  description: String
  is_editable: Boolean!
  is_default: Boolean!
  is_public: Boolean!
  color: String!
  sort_order: Int!
  id_user: ID!
  created_at: DateTime!
  updated_at: DateTime
  # Relations
  user: User
  books: [BookHasLibrary!]!
  stats: LibraryStats
}
