# Type pour représenter une demande de réinitialisation de mot de passe
 type PasswordReset {
  id_passwordReset: ID!
  email: String!
  resetCode: String
  created_at: DateTime
  updated_at: DateTime
}
