# Type pour représenter un rapport
type Report {
  id_report: ID!
  id_user: String!
  report_type: String!
  reported_id: String!
  reason: String!
  status: String!
  details: String!
  created_at: Date!
  updated_at: Date
  # Relations
  whistleblower: User
  reported: User
}

