# Type pour représenter un utilisateur
type User {
  id_user: ID!
  name: String
  email: String!
  pseudo: String!
  id_role: String
  id_status: Int!
  refresh_token: String, 
  last_login: DateTime, 
  created_at: Date!
  updated_at: Date
  # Relations
  role: Role
  status: Status
  }

